# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255, verbose_name='')),
                ('longitude', models.CharField(max_length=255, verbose_name='')),
                ('hostname', models.CharField(max_length=255, verbose_name='')),
                ('city', models.CharField(max_length=255, verbose_name='')),
                ('city_code', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('region', models.CharField(max_length=255, verbose_name='')),
                ('region_code', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('country', models.CharField(max_length=255, verbose_name='')),
                ('country_code', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('continent', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('continent_code', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('org', models.CharField(max_length=255, verbose_name='')),
            ],
            options={
                'verbose_name': 'Geolocation',
                'verbose_name_plural': 'Geolocations',
            },
        ),
        migrations.CreateModel(
            name='GeolocationCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='')),
                ('geolocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meerkat.Geolocation', verbose_name='')),
            ],
            options={
                'verbose_name': 'Geolocation check',
                'verbose_name_plural': 'Geolocation checks',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='')),
                ('datetime', models.DateTimeField(blank=True, verbose_name='')),
                ('timezone', models.CharField(blank=True, max_length=10, verbose_name='')),
                ('url', models.URLField(blank=True, verbose_name='')),
                ('status_code', models.SmallIntegerField(blank=True, verbose_name='')),
                ('user_agent', models.TextField(blank=True, verbose_name='')),
                ('referrer', models.TextField(blank=True, verbose_name='')),
                ('upstream', models.TextField(blank=True, verbose_name='')),
                ('host', models.TextField(blank=True, verbose_name='')),
                ('server', models.TextField(blank=True, verbose_name='')),
                ('verb', models.CharField(blank=True, max_length=10, verbose_name='')),
                ('protocol', models.CharField(blank=True, max_length=10, verbose_name='')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='')),
                ('file_type', models.CharField(blank=True, max_length=20, verbose_name='')),
                ('https', models.BooleanField(default=False, verbose_name='')),
                ('bytes_sent', models.IntegerField(blank=True, verbose_name='')),
                ('error', models.BooleanField(default=False, verbose_name='')),
                ('level', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('message', models.TextField(blank=True, verbose_name='')),
                ('geolocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meerkat.Geolocation', verbose_name='')),
            ],
            options={
                'verbose_name': 'Request log',
                'verbose_name_plural': 'Request logs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='geolocation',
            unique_together=set([('latitude', 'longitude', 'hostname', 'city', 'region', 'country', 'org')]),
        ),
    ]
