# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meerkat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipinfo',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlog',
            name='request_body',
            field=models.TextField(blank=True, verbose_name='Request body'),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='suspicious',
            field=models.NullBooleanField(verbose_name='Suspicious'),
        ),
        migrations.AlterField(
            model_name='ipinfo',
            name='proxy',
            field=models.NullBooleanField(verbose_name='Proxy'),
        ),
        migrations.AlterField(
            model_name='ipinfocheck',
            name='ip_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_check', to='meerkat.IPInfo', verbose_name='IPInfo'),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='https',
            field=models.NullBooleanField(verbose_name='HTTPS'),
        ),
        migrations.AlterUniqueTogether(
            name='ipinfo',
            unique_together=set([('ip_address', 'continent', 'continent_code', 'country', 'country_code', 'region', 'region_code', 'city', 'city_code', 'latitude', 'longitude', 'org', 'asn', 'isp', 'proxy', 'hostname')]),
        ),
    ]
